### PR TITLE
Updated to latest rust

### PR DESCRIPTION
**Pull request by gchp**

### CODE REVIEW

**Comment by reem** [comment]
A few more changes are needed, primarily an additional `plugin` feature gate is needed and some changes to the tests to get rid of uint/int warnings.

**Comment by gchp** [comment]
Strange, those errors don't show up for me...

Will make the changes now, anyways.

**Comment by reem** [comment]
I'm just going off the travis build, I haven't actually pulled this down locally.

**Comment by gchp** [comment]
Strange, I'm using the same version of `rustc` as travis, and it didn't fail for me. Anyways, updated just there.

**Comment by reem** [comment]
Thank you!

**Pull request merged**
