### PR TITLE
Add modifier function wrapper

### PR DESCRIPTION
**Pull request by SCareAngel**
Allow to modify values `&mut T` values with functions/closures that implements `FnOnce(T) -> T`

### CODE REVIEW

**Comment by reem** [comment]
Unfortunately, this is not safe. If the modifying function panics, the &mut T will be left pointing to uninitialized memory, causing undefined behavior.

**Comment by SCareAngel** [comment]
So there is no other way I guess.

**Comment by reem** [comment]
@SCareAngel you might be interested in the `take_mut` crate (crates.io/crates/take_mut) which provides a similar API.

**Comment by SCareAngel** [comment]
@reem, it is interesting. While doing exactly the same it also terminate the program in case of sudden panic. So it can be used with caution. Thank you for link

**Pull request closed without merging**
